language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27
    - python: 2.7
      env: TOX_ENV=py27-django18
    - python: 2.7
      env: TOX_ENV=py27-django111
    - python: 3.6
      env: TOX_ENV=py36
    - python: 3.6
      env: TOX_ENV=py36-django18
    - python: 3.6
      env: TOX_ENV=py36-djangostable
    - env: TOX_ENV=flake8

install:
  - pip install tox codecov

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
